# Generated by Django 5.2.16 on 2026-08-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profilepic.png", upload_to="profile_pictures"
            ),
        ),
    ]
