# Generated by Django 5.2.16 on 2026-08-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.CharField(
                default="https://img.freepik.com/premium-psd/plate-food-with-variety-ingredients-transparent-background_679658-77415.jpg",
                max_length=600,
            ),
        ),
    ]
